### ISSUE TITLE
Error:Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by ulamnet** [pushbit/dining-out#2]
Error:Configuration with name 'default' not found. in android studio

**Comment by talhaqamar** [comment]
getting the same error.Have you solved it ? if yes please post solution too.thanks

**Comment by pushbit** [comment]
Will you please add reproduction steps?  For example, are you using one of the import functions in Android Studio and then this error is displayed when it's trying to build the project?

**Comment by talhaqamar** [comment]
I am using latest version of Android Studio with everything updated upto latest SDK etc.I simply import the project after downloading and its shows the same error.
One more thing in dependencies you included all the jars files in the lib folder but i couldn't found the lib folder

![screen shot 2015-10-31 at 3 25 30 am](https://cloud.githubusercontent.com/assets/2019864/10859455/51390062-7f7f-11e5-9862-0a592770ebb1.png)

**Comment by pushbit** [comment]
Thanks, I was able to reproduce it.  The issue is that I develop Dining Out and Sprockets simultaneously, so for convenience I directly reference the (local) Sprockets library project instead of the (remote) Maven dependency.  Since you, understandably, don't have a local Sprockets project, you can comment out that line and add the remote dependency like below.

```groovy
    //compile project(':sprockets')
    compile 'net.sf.sprockets:sprockets-android:2.6.0'
```

Sorry for this confusion.  I'll try and figure out a way to accommodate both my local dev environment and people who just want to import Dining Out.

**Comment by talhaqamar** [comment]
Thank you it solves the problem :+1:

**Comment by talhaqamar** [comment]
could you please add the project which is working for you fine into dropbox and share the link.because i cant able to compile yours.thanks

**Comment by pushbit** [comment]
I'm not sure I understand what the problem is.  What is your goal and what is the specific compile problem that you are having?

**Comment by talhaqamar** [comment]
This is the error i am getting 
![screen shot 2015-11-02 at 3 34 45 am](https://cloud.githubusercontent.com/assets/2019864/10871786/d518a81c-8112-11e5-9e2d-a139b418b013.png)
These are the warnings
![screen shot 2015-11-02 at 3 35 00 am](https://cloud.githubusercontent.com/assets/2019864/10871787/d7c73394-8112-11e5-8296-d87bc57dfd88.png)

**Comment by pushbit** [comment]
Sorry, I don't know why you're getting that error about multi-dex.  The project doesn't use multi-dex at all.  The warnings can be ignored.
